import time
import numpy as np
import pandas as pd
from pathlib import Path
from shared.logger import get_logger
from shared.io_utils import load_pickle

class TensorDataLoader:
    """
    Loads and validates the preprocessed EEG and fNIRS tensor epoch files 
    generated by Member A.
    """

    def __init__(self, config: dict):
        self.config = config
        self.logger = get_logger("TensorDataLoader")
        self.processed_dir = Path(config['data'].get('processed_dir', 'data/processed'))

    def load_subject(self, subject_id: int) -> tuple[np.ndarray, np.ndarray]:
        """
        Loads the pre-epoched tensors for a specific subject.
        Returns: (eeg_epochs, fnirs_epochs)
        """
        t0 = time.perf_counter()
        self.logger.debug(f"[TensorDataLoader.load_subject] starting for subject {subject_id}")
        
        subj_str = f"00{subject_id}"
        eeg_path = self.processed_dir / f"eeg_epochs_subj{subj_str}.pkl"
        fnirs_path = self.processed_dir / f"fnirs_epochs_subj{subj_str}.pkl"
        
        if not eeg_path.exists() or not fnirs_path.exists():
            raise FileNotFoundError(f"Missing data for subject {subject_id}. Looked for:\n- {eeg_path}\n- {fnirs_path}")
            
        eeg_epochs_obj = load_pickle(str(eeg_path))
        fnirs_epochs = load_pickle(str(fnirs_path))
        
        # Extract numpy data from MNE Epochs object
        eeg_epochs = eeg_epochs_obj.get_data(copy=False)
        
        self._verify_alignment(eeg_epochs, fnirs_epochs, subject_id)
        
        # Validate no NaNs
        if np.isnan(eeg_epochs).any():
            self.logger.warning(f"Subject {subject_id} EEG contains NaNs. Filling with 0.")
            eeg_epochs = np.nan_to_num(eeg_epochs)
            
        if np.isnan(fnirs_epochs).any():
            self.logger.warning(f"Subject {subject_id} fNIRS contains NaNs. Filling with 0.")
            fnirs_epochs = np.nan_to_num(fnirs_epochs)
        
        elapsed = time.perf_counter() - t0
        self.logger.debug(f"[TensorDataLoader.load_subject] done in {elapsed:.2f}s")
        return eeg_epochs, fnirs_epochs

    def _verify_alignment(self, eeg_epochs: np.ndarray, fnirs_epochs: np.ndarray, subject_id: int) -> None:
        """Checks epoch counts match."""
        if eeg_epochs.shape[0] != fnirs_epochs.shape[0]:
            raise ValueError(f"Alignment Error for Subject {subject_id}: EEG epochs ({eeg_epochs.shape[0]}) != fNIRS epochs ({fnirs_epochs.shape[0]}).")
        
        # Verify shapes
        if eeg_epochs.shape[1:] != (9, 256):
            raise ValueError(f"Invalid EEG shape for Subject {subject_id}: Expected (N, 9, 256), got {eeg_epochs.shape}")
        if fnirs_epochs.shape[1:] != (8, 10):
            raise ValueError(f"Invalid fNIRS shape for Subject {subject_id}: Expected (N, 8, 10), got {fnirs_epochs.shape}")
